version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-sphinx-theme"
    assignees:
      - "pyansys-ci-bot"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(pip)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    assignees:
      - "pyansys-ci-bot"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(actions)"
