# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import adaptive_settings_pb2 as adaptive__settings__pb2
import edb_messages_pb2 as edb__messages__pb2


class AdaptiveSettingsServiceStub(object):
  """DEPRECATED: use SimulationSetupService instead
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAdaptiveFrequencyDataList = channel.unary_unary(
        '/ansys.api.edb.v1.AdaptiveSettingsService/GetAdaptiveFrequencyDataList',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=adaptive__settings__pb2.AdaptiveFrequencyDataListMessage.FromString,
        )
    self.SetAdaptiveFrequencyDataList = channel.unary_unary(
        '/ansys.api.edb.v1.AdaptiveSettingsService/SetAdaptiveFrequencyDataList',
        request_serializer=adaptive__settings__pb2.SetAdaptiveFrequencyDataListMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )


class AdaptiveSettingsServiceServicer(object):
  """DEPRECATED: use SimulationSetupService instead
  """

  def GetAdaptiveFrequencyDataList(self, request, context):
    """Gets the list of AdaptiveFrequencyData for the active adaptive type
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetAdaptiveFrequencyDataList(self, request, context):
    """Sets the list of AdaptiveFrequencyData for the active adaptive type
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdaptiveSettingsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAdaptiveFrequencyDataList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAdaptiveFrequencyDataList,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=adaptive__settings__pb2.AdaptiveFrequencyDataListMessage.SerializeToString,
      ),
      'SetAdaptiveFrequencyDataList': grpc.unary_unary_rpc_method_handler(
          servicer.SetAdaptiveFrequencyDataList,
          request_deserializer=adaptive__settings__pb2.SetAdaptiveFrequencyDataListMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.AdaptiveSettingsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
