# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cell.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cell.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncell.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"\x80\x01\n\x13\x43\x65llCreationMessage\x12\x31\n\x08\x64\x61tabase\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.ansys.api.edb.v1.CellType\x12\x0c\n\x04name\x18\x03 \x01(\t\"P\n\rExtentMessage\x12-\n\x05value\x18\x01 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x10\n\x08\x61\x62solute\x18\x02 \x01(\x08\"\xac\x04\n\x16\x43\x65llHfssExtentsMessage\x12-\n\x04\x63\x65ll\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x35\n\ndielectric\x18\x02 \x01(\x0b\x32\x1f.ansys.api.edb.v1.ExtentMessageH\x00\x12<\n\x11\x61irbox_horizontal\x18\x03 \x01(\x0b\x32\x1f.ansys.api.edb.v1.ExtentMessageH\x01\x12\x43\n\x18\x61irbox_vertical_positive\x18\x04 \x01(\x0b\x32\x1f.ansys.api.edb.v1.ExtentMessageH\x02\x12\x43\n\x18\x61irbox_vertical_negative\x18\x05 \x01(\x0b\x32\x1f.ansys.api.edb.v1.ExtentMessageH\x03\x12?\n\x19\x61irbox_truncate_at_ground\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x04\x42\x15\n\x13optional_dielectricB\x1c\n\x1aoptional_airbox_horizontalB#\n!optional_airbox_vertical_positiveB#\n!optional_airbox_vertical_negativeB$\n\"optional_airbox_truncate_at_ground*0\n\x08\x43\x65llType\x12\x10\n\x0c\x43IRCUIT_CELL\x10\x00\x12\x12\n\x0e\x46OOTPRINT_CELL\x10\x01\x32\x8c\x02\n\x0b\x43\x65llService\x12R\n\x06\x43reate\x12%.ansys.api.edb.v1.CellCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12O\n\tGetLayout\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12X\n\x0eSetHfssExtents\x12(.ansys.api.edb.v1.CellHfssExtentsMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])

_CELLTYPE = _descriptor.EnumDescriptor(
  name='CellType',
  full_name='ansys.api.edb.v1.CellType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CIRCUIT_CELL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOOTPRINT_CELL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=824,
  serialized_end=872,
)
_sym_db.RegisterEnumDescriptor(_CELLTYPE)

CellType = enum_type_wrapper.EnumTypeWrapper(_CELLTYPE)
CIRCUIT_CELL = 0
FOOTPRINT_CELL = 1



_CELLCREATIONMESSAGE = _descriptor.Descriptor(
  name='CellCreationMessage',
  full_name='ansys.api.edb.v1.CellCreationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='ansys.api.edb.v1.CellCreationMessage.database', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ansys.api.edb.v1.CellCreationMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.CellCreationMessage.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=181,
)


_EXTENTMESSAGE = _descriptor.Descriptor(
  name='ExtentMessage',
  full_name='ansys.api.edb.v1.ExtentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ansys.api.edb.v1.ExtentMessage.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='absolute', full_name='ansys.api.edb.v1.ExtentMessage.absolute', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=263,
)


_CELLHFSSEXTENTSMESSAGE = _descriptor.Descriptor(
  name='CellHfssExtentsMessage',
  full_name='ansys.api.edb.v1.CellHfssExtentsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.cell', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dielectric', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.dielectric', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airbox_horizontal', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.airbox_horizontal', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airbox_vertical_positive', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.airbox_vertical_positive', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airbox_vertical_negative', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.airbox_vertical_negative', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airbox_truncate_at_ground', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.airbox_truncate_at_ground', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_dielectric', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.optional_dielectric',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_airbox_horizontal', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.optional_airbox_horizontal',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_airbox_vertical_positive', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.optional_airbox_vertical_positive',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_airbox_vertical_negative', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.optional_airbox_vertical_negative',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_airbox_truncate_at_ground', full_name='ansys.api.edb.v1.CellHfssExtentsMessage.optional_airbox_truncate_at_ground',
      index=4, containing_type=None, fields=[]),
  ],
  serialized_start=266,
  serialized_end=822,
)

_CELLCREATIONMESSAGE.fields_by_name['database'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_CELLCREATIONMESSAGE.fields_by_name['type'].enum_type = _CELLTYPE
_EXTENTMESSAGE.fields_by_name['value'].message_type = edb__messages__pb2._VALUEMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['cell'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['dielectric'].message_type = _EXTENTMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_horizontal'].message_type = _EXTENTMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_positive'].message_type = _EXTENTMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_negative'].message_type = _EXTENTMESSAGE
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_truncate_at_ground'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_dielectric'].fields.append(
  _CELLHFSSEXTENTSMESSAGE.fields_by_name['dielectric'])
_CELLHFSSEXTENTSMESSAGE.fields_by_name['dielectric'].containing_oneof = _CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_dielectric']
_CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_horizontal'].fields.append(
  _CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_horizontal'])
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_horizontal'].containing_oneof = _CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_horizontal']
_CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_vertical_positive'].fields.append(
  _CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_positive'])
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_positive'].containing_oneof = _CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_vertical_positive']
_CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_vertical_negative'].fields.append(
  _CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_negative'])
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_vertical_negative'].containing_oneof = _CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_vertical_negative']
_CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_truncate_at_ground'].fields.append(
  _CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_truncate_at_ground'])
_CELLHFSSEXTENTSMESSAGE.fields_by_name['airbox_truncate_at_ground'].containing_oneof = _CELLHFSSEXTENTSMESSAGE.oneofs_by_name['optional_airbox_truncate_at_ground']
DESCRIPTOR.message_types_by_name['CellCreationMessage'] = _CELLCREATIONMESSAGE
DESCRIPTOR.message_types_by_name['ExtentMessage'] = _EXTENTMESSAGE
DESCRIPTOR.message_types_by_name['CellHfssExtentsMessage'] = _CELLHFSSEXTENTSMESSAGE
DESCRIPTOR.enum_types_by_name['CellType'] = _CELLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CellCreationMessage = _reflection.GeneratedProtocolMessageType('CellCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _CELLCREATIONMESSAGE,
  '__module__' : 'cell_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.CellCreationMessage)
  })
_sym_db.RegisterMessage(CellCreationMessage)

ExtentMessage = _reflection.GeneratedProtocolMessageType('ExtentMessage', (_message.Message,), {
  'DESCRIPTOR' : _EXTENTMESSAGE,
  '__module__' : 'cell_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.ExtentMessage)
  })
_sym_db.RegisterMessage(ExtentMessage)

CellHfssExtentsMessage = _reflection.GeneratedProtocolMessageType('CellHfssExtentsMessage', (_message.Message,), {
  'DESCRIPTOR' : _CELLHFSSEXTENTSMESSAGE,
  '__module__' : 'cell_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.CellHfssExtentsMessage)
  })
_sym_db.RegisterMessage(CellHfssExtentsMessage)



_CELLSERVICE = _descriptor.ServiceDescriptor(
  name='CellService',
  full_name='ansys.api.edb.v1.CellService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=875,
  serialized_end=1143,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.CellService.Create',
    index=0,
    containing_service=None,
    input_type=_CELLCREATIONMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLayout',
    full_name='ansys.api.edb.v1.CellService.GetLayout',
    index=1,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetHfssExtents',
    full_name='ansys.api.edb.v1.CellService.SetHfssExtents',
    index=2,
    containing_service=None,
    input_type=_CELLHFSSEXTENTSMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CELLSERVICE)

DESCRIPTOR.services_by_name['CellService'] = _CELLSERVICE

# @@protoc_insertion_point(module_scope)
