# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ansys.api.edb.v1.edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2
import ansys.api.edb.v1.refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ircle.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\x1a\nrefs.proto\"\xbc\x02\n\x15\x43ircleCreationMessage\x12/\n\x06layout\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x30\n\x05layer\x18\x02 \x01(\x0b\x32!.ansys.api.edb.v1.LayerRefMessage\x12,\n\x03net\x18\x03 \x01(\x0b\x32\x1f.ansys.api.edb.v1.NetRefMessage\x12\x30\n\x08\x63\x65nter_x\x18\x04 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x30\n\x08\x63\x65nter_y\x18\x05 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12.\n\x06radius\x18\x06 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\"\xba\x01\n\x13\x43ircleRenderMessage\x12\x30\n\x08\x63\x65nter_x\x18\x01 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x30\n\x08\x63\x65nter_y\x18\x02 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12.\n\x06radius\x18\x03 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x0f\n\x07is_hole\x18\x04 \x01(\x08\"\xad\x01\n\x17\x43ircleParametersMessage\x12\x30\n\x08\x63\x65nter_x\x18\x01 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x30\n\x08\x63\x65nter_y\x18\x02 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12.\n\x06radius\x18\x03 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\"\x8c\x01\n\x1aSetCircleParametersMessage\x12/\n\x06target\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12=\n\nparameters\x18\x02 \x01(\x0b\x32).ansys.api.edb.v1.CircleParametersMessage2\xf5\x02\n\rCircleService\x12T\n\x06\x43reate\x12\'.ansys.api.edb.v1.CircleCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12R\n\x06Render\x12%.ansys.api.edb.v1.CircleRenderMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12]\n\rGetParameters\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a).ansys.api.edb.v1.CircleParametersMessage\"\x00\x12[\n\rSetParameters\x12,.ansys.api.edb.v1.SetCircleParametersMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x62\x06proto3')



_CIRCLECREATIONMESSAGE = DESCRIPTOR.message_types_by_name['CircleCreationMessage']
_CIRCLERENDERMESSAGE = DESCRIPTOR.message_types_by_name['CircleRenderMessage']
_CIRCLEPARAMETERSMESSAGE = DESCRIPTOR.message_types_by_name['CircleParametersMessage']
_SETCIRCLEPARAMETERSMESSAGE = DESCRIPTOR.message_types_by_name['SetCircleParametersMessage']
CircleCreationMessage = _reflection.GeneratedProtocolMessageType('CircleCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLECREATIONMESSAGE,
  '__module__' : 'circle_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.CircleCreationMessage)
  })
_sym_db.RegisterMessage(CircleCreationMessage)

CircleRenderMessage = _reflection.GeneratedProtocolMessageType('CircleRenderMessage', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLERENDERMESSAGE,
  '__module__' : 'circle_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.CircleRenderMessage)
  })
_sym_db.RegisterMessage(CircleRenderMessage)

CircleParametersMessage = _reflection.GeneratedProtocolMessageType('CircleParametersMessage', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLEPARAMETERSMESSAGE,
  '__module__' : 'circle_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.CircleParametersMessage)
  })
_sym_db.RegisterMessage(CircleParametersMessage)

SetCircleParametersMessage = _reflection.GeneratedProtocolMessageType('SetCircleParametersMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETCIRCLEPARAMETERSMESSAGE,
  '__module__' : 'circle_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SetCircleParametersMessage)
  })
_sym_db.RegisterMessage(SetCircleParametersMessage)

_CIRCLESERVICE = DESCRIPTOR.services_by_name['CircleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CIRCLECREATIONMESSAGE._serialized_start=67
  _CIRCLECREATIONMESSAGE._serialized_end=383
  _CIRCLERENDERMESSAGE._serialized_start=386
  _CIRCLERENDERMESSAGE._serialized_end=572
  _CIRCLEPARAMETERSMESSAGE._serialized_start=575
  _CIRCLEPARAMETERSMESSAGE._serialized_end=748
  _SETCIRCLEPARAMETERSMESSAGE._serialized_start=751
  _SETCIRCLEPARAMETERSMESSAGE._serialized_end=891
  _CIRCLESERVICE._serialized_start=894
  _CIRCLESERVICE._serialized_end=1267
# @@protoc_insertion_point(module_scope)
