# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64\x61tabase.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"t\n\x13OpenDatabaseMessage\x12.\n\x08\x65\x64\x62_path\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\tread_only\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue2\xc5\x05\n\x0f\x44\x61tabaseService\x12I\n\x06\x43reate\x12\x1c.google.protobuf.StringValue\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12P\n\x04Open\x12%.ansys.api.edb.v1.OpenDatabaseMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12\x44\n\x06\x44\x65lete\x12\x1c.google.protobuf.StringValue\x1a\x1a.google.protobuf.BoolValue\"\x00\x12\x45\n\x04Save\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12\x46\n\x05\x43lose\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12K\n\nIsReadOnly\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12^\n\x0eGetTopCircuits\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a).ansys.api.edb.v1.EDBObjCollectionMessage\"\x00\x12G\n\x05GetId\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1b.google.protobuf.Int64Value\"\x00\x12J\n\x08\x46indById\x12\x1b.google.protobuf.Int64Value\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])




_OPENDATABASEMESSAGE = _descriptor.Descriptor(
  name='OpenDatabaseMessage',
  full_name='ansys.api.edb.v1.OpenDatabaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edb_path', full_name='ansys.api.edb.v1.OpenDatabaseMessage.edb_path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_only', full_name='ansys.api.edb.v1.OpenDatabaseMessage.read_only', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=172,
)

_OPENDATABASEMESSAGE.fields_by_name['edb_path'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_OPENDATABASEMESSAGE.fields_by_name['read_only'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
DESCRIPTOR.message_types_by_name['OpenDatabaseMessage'] = _OPENDATABASEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenDatabaseMessage = _reflection.GeneratedProtocolMessageType('OpenDatabaseMessage', (_message.Message,), {
  'DESCRIPTOR' : _OPENDATABASEMESSAGE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.OpenDatabaseMessage)
  })
_sym_db.RegisterMessage(OpenDatabaseMessage)



_DATABASESERVICE = _descriptor.ServiceDescriptor(
  name='DatabaseService',
  full_name='ansys.api.edb.v1.DatabaseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=175,
  serialized_end=884,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.DatabaseService.Create',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Open',
    full_name='ansys.api.edb.v1.DatabaseService.Open',
    index=1,
    containing_service=None,
    input_type=_OPENDATABASEMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='ansys.api.edb.v1.DatabaseService.Delete',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='ansys.api.edb.v1.DatabaseService.Save',
    index=3,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='ansys.api.edb.v1.DatabaseService.Close',
    index=4,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IsReadOnly',
    full_name='ansys.api.edb.v1.DatabaseService.IsReadOnly',
    index=5,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTopCircuits',
    full_name='ansys.api.edb.v1.DatabaseService.GetTopCircuits',
    index=6,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=edb__messages__pb2._EDBOBJCOLLECTIONMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetId',
    full_name='ansys.api.edb.v1.DatabaseService.GetId',
    index=7,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._INT64VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindById',
    full_name='ansys.api.edb.v1.DatabaseService.FindById',
    index=8,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT64VALUE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASESERVICE)

DESCRIPTOR.services_by_name['DatabaseService'] = _DATABASESERVICE

# @@protoc_insertion_point(module_scope)
