# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definition_obj.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='definition_obj.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x64\x65\x66inition_obj.proto\x12\x10\x61nsys.api.edb.v1*\xbf\x01\n\x11\x44\x65\x66initionObjType\x12\x10\n\x0cPADSTACK_DEF\x10\x00\x12\x11\n\rCOMPONENT_DEF\x10\x01\x12\x10\n\x0c\x42ONDWIRE_DEF\x10\x02\x12\x10\n\x0cMATERIAL_DEF\x10\x03\x12\x0f\n\x0b\x44\x41TASET_DEF\x10\x04\x12\x0f\n\x0bPACKAGE_DEF\x10\x05\x12\x19\n\x15\x44\x45\x46INITION_TYPE_COUNT\x10\x06\x12$\n\x17INVALID_DEFINITION_TYPE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3')
)

_DEFINITIONOBJTYPE = _descriptor.EnumDescriptor(
  name='DefinitionObjType',
  full_name='ansys.api.edb.v1.DefinitionObjType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PADSTACK_DEF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPONENT_DEF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BONDWIRE_DEF', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATERIAL_DEF', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATASET_DEF', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PACKAGE_DEF', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEFINITION_TYPE_COUNT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DEFINITION_TYPE', index=7, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=43,
  serialized_end=234,
)
_sym_db.RegisterEnumDescriptor(_DEFINITIONOBJTYPE)

DefinitionObjType = enum_type_wrapper.EnumTypeWrapper(_DEFINITIONOBJTYPE)
PADSTACK_DEF = 0
COMPONENT_DEF = 1
BONDWIRE_DEF = 2
MATERIAL_DEF = 3
DATASET_DEF = 4
PACKAGE_DEF = 5
DEFINITION_TYPE_COUNT = 6
INVALID_DEFINITION_TYPE = -1


DESCRIPTOR.enum_types_by_name['DefinitionObjType'] = _DEFINITIONOBJTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
