# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_iterator_pb2 as edb__iterator__pb2
import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EDBIteratorServiceStub(object):
  """EDB Iterator service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NextChunk = channel.unary_unary(
        '/ansys.api.edb.v1.EDBIteratorService/NextChunk',
        request_serializer=edb__iterator__pb2.EDBIteratorMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjCollectionMessage.FromString,
        )
    self.Cleanup = channel.unary_unary(
        '/ansys.api.edb.v1.EDBIteratorService/Cleanup',
        request_serializer=edb__iterator__pb2.EDBIteratorMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class EDBIteratorServiceServicer(object):
  """EDB Iterator service definition
  """

  def NextChunk(self, request, context):
    """Gets the next chunk of edb objs
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Cleanup(self, request, context):
    """Cleans up the iterator pointer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EDBIteratorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NextChunk': grpc.unary_unary_rpc_method_handler(
          servicer.NextChunk,
          request_deserializer=edb__iterator__pb2.EDBIteratorMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjCollectionMessage.SerializeToString,
      ),
      'Cleanup': grpc.unary_unary_rpc_method_handler(
          servicer.Cleanup,
          request_deserializer=edb__iterator__pb2.EDBIteratorMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.EDBIteratorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
