# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edb_iterator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edb_iterator.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x65\x64\x62_iterator.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"]\n\x12\x45\x44\x42IteratorMessage\x12\x18\n\x10impl_ptr_address\x18\x01 \x01(\x04\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.ansys.api.edb.v1.iterator_type*#\n\riterator_type\x12\x12\n\x0ePRIMITIVE_ITER\x10\x00\x32\xbf\x01\n\x12\x45\x44\x42IteratorService\x12^\n\tNextChunk\x12$.ansys.api.edb.v1.EDBIteratorMessage\x1a).ansys.api.edb.v1.EDBObjCollectionMessage\"\x00\x12I\n\x07\x43leanup\x12$.ansys.api.edb.v1.EDBIteratorMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])

_ITERATOR_TYPE = _descriptor.EnumDescriptor(
  name='iterator_type',
  full_name='ansys.api.edb.v1.iterator_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIMITIVE_ITER', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_ITERATOR_TYPE)

iterator_type = enum_type_wrapper.EnumTypeWrapper(_ITERATOR_TYPE)
PRIMITIVE_ITER = 0



_EDBITERATORMESSAGE = _descriptor.Descriptor(
  name='EDBIteratorMessage',
  full_name='ansys.api.edb.v1.EDBIteratorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='impl_ptr_address', full_name='ansys.api.edb.v1.EDBIteratorMessage.impl_ptr_address', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ansys.api.edb.v1.EDBIteratorMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=153,
)

_EDBITERATORMESSAGE.fields_by_name['type'].enum_type = _ITERATOR_TYPE
DESCRIPTOR.message_types_by_name['EDBIteratorMessage'] = _EDBITERATORMESSAGE
DESCRIPTOR.enum_types_by_name['iterator_type'] = _ITERATOR_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EDBIteratorMessage = _reflection.GeneratedProtocolMessageType('EDBIteratorMessage', (_message.Message,), {
  'DESCRIPTOR' : _EDBITERATORMESSAGE,
  '__module__' : 'edb_iterator_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.EDBIteratorMessage)
  })
_sym_db.RegisterMessage(EDBIteratorMessage)



_EDBITERATORSERVICE = _descriptor.ServiceDescriptor(
  name='EDBIteratorService',
  full_name='ansys.api.edb.v1.EDBIteratorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=193,
  serialized_end=384,
  methods=[
  _descriptor.MethodDescriptor(
    name='NextChunk',
    full_name='ansys.api.edb.v1.EDBIteratorService.NextChunk',
    index=0,
    containing_service=None,
    input_type=_EDBITERATORMESSAGE,
    output_type=edb__messages__pb2._EDBOBJCOLLECTIONMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Cleanup',
    full_name='ansys.api.edb.v1.EDBIteratorService.Cleanup',
    index=1,
    containing_service=None,
    input_type=_EDBITERATORMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDBITERATORSERVICE)

DESCRIPTOR.services_by_name['EDBIteratorService'] = _EDBITERATORSERVICE

# @@protoc_insertion_point(module_scope)
