# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edb_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.wrappers_pb2 import *
from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='edb_messages.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x65\x64\x62_messages.proto\x12\x10\x61nsys.api.edb.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0cValueMessage\x12\r\n\x05value\x18\x01 \x01(\x01\")\n\rEDBObjMessage\x12\x18\n\x10impl_ptr_address\x18\x01 \x01(\x04\"V\n\x17\x45\x44\x42ObjCollectionMessage\x12;\n\x12\x65\x64\x62_obj_collection\x18\x01 \x03(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessageP\x00P\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,],
  public_dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_VALUEMESSAGE = _descriptor.Descriptor(
  name='ValueMessage',
  full_name='ansys.api.edb.v1.ValueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ansys.api.edb.v1.ValueMessage.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=130,
)


_EDBOBJMESSAGE = _descriptor.Descriptor(
  name='EDBObjMessage',
  full_name='ansys.api.edb.v1.EDBObjMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='impl_ptr_address', full_name='ansys.api.edb.v1.EDBObjMessage.impl_ptr_address', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=173,
)


_EDBOBJCOLLECTIONMESSAGE = _descriptor.Descriptor(
  name='EDBObjCollectionMessage',
  full_name='ansys.api.edb.v1.EDBObjCollectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edb_obj_collection', full_name='ansys.api.edb.v1.EDBObjCollectionMessage.edb_obj_collection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=261,
)

_EDBOBJCOLLECTIONMESSAGE.fields_by_name['edb_obj_collection'].message_type = _EDBOBJMESSAGE
DESCRIPTOR.message_types_by_name['ValueMessage'] = _VALUEMESSAGE
DESCRIPTOR.message_types_by_name['EDBObjMessage'] = _EDBOBJMESSAGE
DESCRIPTOR.message_types_by_name['EDBObjCollectionMessage'] = _EDBOBJCOLLECTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueMessage = _reflection.GeneratedProtocolMessageType('ValueMessage', (_message.Message,), {
  'DESCRIPTOR' : _VALUEMESSAGE,
  '__module__' : 'edb_messages_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.ValueMessage)
  })
_sym_db.RegisterMessage(ValueMessage)

EDBObjMessage = _reflection.GeneratedProtocolMessageType('EDBObjMessage', (_message.Message,), {
  'DESCRIPTOR' : _EDBOBJMESSAGE,
  '__module__' : 'edb_messages_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.EDBObjMessage)
  })
_sym_db.RegisterMessage(EDBObjMessage)

EDBObjCollectionMessage = _reflection.GeneratedProtocolMessageType('EDBObjCollectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _EDBOBJCOLLECTIONMESSAGE,
  '__module__' : 'edb_messages_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.EDBObjCollectionMessage)
  })
_sym_db.RegisterMessage(EDBObjCollectionMessage)


# @@protoc_insertion_point(module_scope)
