# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layer_collection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='layer_collection.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16layer_collection.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"S\n\x1cLayerCollectionCreateMessage\x12\x33\n\x04mode\x18\x01 \x01(\x0e\x32%.ansys.api.edb.v1.LayerCollectionMode\"~\n\x10\x41\x64\x64LayersMessage\x12\x39\n\x10layer_collection\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12/\n\x06layers\x18\x02 \x03(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\"a\n\x16\x46indLayerByNameMessage\x12\x39\n\x10layer_collection\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x0c\n\x04name\x18\x02 \x01(\t*C\n\x13LayerCollectionMode\x12\x0c\n\x08LAMINATE\x10\x00\x12\x0f\n\x0bOVERLAPPING\x10\x01\x12\r\n\tMULTIZONE\x10\x02\x32\xe5\x02\n\x16LayerCollectionService\x12\x44\n\x07\x43leanup\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x16.google.protobuf.Empty\"\x00\x12[\n\x06\x43reate\x12..ansys.api.edb.v1.LayerCollectionCreateMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12M\n\tAddLayers\x12\".ansys.api.edb.v1.AddLayersMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12Y\n\nFindByName\x12(.ansys.api.edb.v1.FindLayerByNameMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])

_LAYERCOLLECTIONMODE = _descriptor.EnumDescriptor(
  name='LayerCollectionMode',
  full_name='ansys.api.edb.v1.LayerCollectionMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAMINATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OVERLAPPING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIZONE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=376,
  serialized_end=443,
)
_sym_db.RegisterEnumDescriptor(_LAYERCOLLECTIONMODE)

LayerCollectionMode = enum_type_wrapper.EnumTypeWrapper(_LAYERCOLLECTIONMODE)
LAMINATE = 0
OVERLAPPING = 1
MULTIZONE = 2



_LAYERCOLLECTIONCREATEMESSAGE = _descriptor.Descriptor(
  name='LayerCollectionCreateMessage',
  full_name='ansys.api.edb.v1.LayerCollectionCreateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ansys.api.edb.v1.LayerCollectionCreateMessage.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=147,
)


_ADDLAYERSMESSAGE = _descriptor.Descriptor(
  name='AddLayersMessage',
  full_name='ansys.api.edb.v1.AddLayersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer_collection', full_name='ansys.api.edb.v1.AddLayersMessage.layer_collection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layers', full_name='ansys.api.edb.v1.AddLayersMessage.layers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=275,
)


_FINDLAYERBYNAMEMESSAGE = _descriptor.Descriptor(
  name='FindLayerByNameMessage',
  full_name='ansys.api.edb.v1.FindLayerByNameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer_collection', full_name='ansys.api.edb.v1.FindLayerByNameMessage.layer_collection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.FindLayerByNameMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=374,
)

_LAYERCOLLECTIONCREATEMESSAGE.fields_by_name['mode'].enum_type = _LAYERCOLLECTIONMODE
_ADDLAYERSMESSAGE.fields_by_name['layer_collection'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_ADDLAYERSMESSAGE.fields_by_name['layers'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_FINDLAYERBYNAMEMESSAGE.fields_by_name['layer_collection'].message_type = edb__messages__pb2._EDBOBJMESSAGE
DESCRIPTOR.message_types_by_name['LayerCollectionCreateMessage'] = _LAYERCOLLECTIONCREATEMESSAGE
DESCRIPTOR.message_types_by_name['AddLayersMessage'] = _ADDLAYERSMESSAGE
DESCRIPTOR.message_types_by_name['FindLayerByNameMessage'] = _FINDLAYERBYNAMEMESSAGE
DESCRIPTOR.enum_types_by_name['LayerCollectionMode'] = _LAYERCOLLECTIONMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerCollectionCreateMessage = _reflection.GeneratedProtocolMessageType('LayerCollectionCreateMessage', (_message.Message,), {
  'DESCRIPTOR' : _LAYERCOLLECTIONCREATEMESSAGE,
  '__module__' : 'layer_collection_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.LayerCollectionCreateMessage)
  })
_sym_db.RegisterMessage(LayerCollectionCreateMessage)

AddLayersMessage = _reflection.GeneratedProtocolMessageType('AddLayersMessage', (_message.Message,), {
  'DESCRIPTOR' : _ADDLAYERSMESSAGE,
  '__module__' : 'layer_collection_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.AddLayersMessage)
  })
_sym_db.RegisterMessage(AddLayersMessage)

FindLayerByNameMessage = _reflection.GeneratedProtocolMessageType('FindLayerByNameMessage', (_message.Message,), {
  'DESCRIPTOR' : _FINDLAYERBYNAMEMESSAGE,
  '__module__' : 'layer_collection_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.FindLayerByNameMessage)
  })
_sym_db.RegisterMessage(FindLayerByNameMessage)



_LAYERCOLLECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='LayerCollectionService',
  full_name='ansys.api.edb.v1.LayerCollectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=446,
  serialized_end=803,
  methods=[
  _descriptor.MethodDescriptor(
    name='Cleanup',
    full_name='ansys.api.edb.v1.LayerCollectionService.Cleanup',
    index=0,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.LayerCollectionService.Create',
    index=1,
    containing_service=None,
    input_type=_LAYERCOLLECTIONCREATEMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddLayers',
    full_name='ansys.api.edb.v1.LayerCollectionService.AddLayers',
    index=2,
    containing_service=None,
    input_type=_ADDLAYERSMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindByName',
    full_name='ansys.api.edb.v1.LayerCollectionService.FindByName',
    index=3,
    containing_service=None,
    input_type=_FINDLAYERBYNAMEMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAYERCOLLECTIONSERVICE)

DESCRIPTOR.services_by_name['LayerCollectionService'] = _LAYERCOLLECTIONSERVICE

# @@protoc_insertion_point(module_scope)
