# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_iterator_pb2 as edb__iterator__pb2
import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import layout_pb2 as layout__pb2


class LayoutServiceStub(object):
  """Cell service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCell = channel.unary_unary(
        '/ansys.api.edb.v1.LayoutService/GetCell',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.GetLayerCollection = channel.unary_unary(
        '/ansys.api.edb.v1.LayoutService/GetLayerCollection',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.SetLayerCollection = channel.unary_unary(
        '/ansys.api.edb.v1.LayoutService/SetLayerCollection',
        request_serializer=layout__pb2.SetLayerCollectionMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.SetLayerCollectionType = channel.unary_unary(
        '/ansys.api.edb.v1.LayoutService/SetLayerCollectionType',
        request_serializer=layout__pb2.SetLayerCollectionTypeMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.GetPrimitiveIter = channel.unary_unary(
        '/ansys.api.edb.v1.LayoutService/GetPrimitiveIter',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__iterator__pb2.EDBIteratorMessage.FromString,
        )


class LayoutServiceServicer(object):
  """Cell service definition
  """

  def GetCell(self, request, context):
    """Gets the cell of the provided layout
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLayerCollection(self, request, context):
    """Gets the layer collection of the layout
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLayerCollection(self, request, context):
    """Sets the layer collection of the layout
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLayerCollectionType(self, request, context):
    """Sets the type of layer collection of the layout
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrimitiveIter(self, request, context):
    """Gets an iterator of the primitives in the layout
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LayoutServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCell': grpc.unary_unary_rpc_method_handler(
          servicer.GetCell,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'GetLayerCollection': grpc.unary_unary_rpc_method_handler(
          servicer.GetLayerCollection,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'SetLayerCollection': grpc.unary_unary_rpc_method_handler(
          servicer.SetLayerCollection,
          request_deserializer=layout__pb2.SetLayerCollectionMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'SetLayerCollectionType': grpc.unary_unary_rpc_method_handler(
          servicer.SetLayerCollectionType,
          request_deserializer=layout__pb2.SetLayerCollectionTypeMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'GetPrimitiveIter': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrimitiveIter,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__iterator__pb2.EDBIteratorMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.LayoutService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
