# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layout_obj.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='layout_obj.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10layout_obj.proto\x12\x10\x61nsys.api.edb.v1*\xaa\x02\n\rLayoutObjType\x12\r\n\tPRIMITIVE\x10\x00\x12\x11\n\rPADSTACK_INST\x10\x01\x12\x08\n\x04TERM\x10\x02\x12\r\n\tTERM_INST\x10\x03\x12\r\n\tCELL_INST\x10\x04\x12\t\n\x05LAYER\x10\x05\x12\x07\n\x03NET\x10\x06\x12\x0c\n\x08PADSTACK\x10\x07\x12\t\n\x05GROUP\x10\x08\x12\r\n\tNET_CLASS\x10\t\x12\x08\n\x04\x43\x45LL\x10\n\x12\x15\n\x11\x44IFFERENTIAL_PAIR\x10\x0b\x12\r\n\tPIN_GROUP\x10\x0c\x12\x15\n\x11VOLTAGE_REGULATOR\x10\r\x12\x10\n\x0c\x45XTENDED_NET\x10\x0e\x12\x19\n\x15LAYOUT_OBJ_TYPE_COUNT\x10\x0f\x12\x1f\n\x12INVALID_LAYOUT_OBJ\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3')
)

_LAYOUTOBJTYPE = _descriptor.EnumDescriptor(
  name='LayoutObjType',
  full_name='ansys.api.edb.v1.LayoutObjType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIMITIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PADSTACK_INST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TERM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TERM_INST', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CELL_INST', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAYER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NET', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PADSTACK', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NET_CLASS', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CELL', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIFFERENTIAL_PAIR', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIN_GROUP', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLTAGE_REGULATOR', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTENDED_NET', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_OBJ_TYPE_COUNT', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_LAYOUT_OBJ', index=16, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=39,
  serialized_end=337,
)
_sym_db.RegisterEnumDescriptor(_LAYOUTOBJTYPE)

LayoutObjType = enum_type_wrapper.EnumTypeWrapper(_LAYOUTOBJTYPE)
PRIMITIVE = 0
PADSTACK_INST = 1
TERM = 2
TERM_INST = 3
CELL_INST = 4
LAYER = 5
NET = 6
PADSTACK = 7
GROUP = 8
NET_CLASS = 9
CELL = 10
DIFFERENTIAL_PAIR = 11
PIN_GROUP = 12
VOLTAGE_REGULATOR = 13
EXTENDED_NET = 14
LAYOUT_OBJ_TYPE_COUNT = 15
INVALID_LAYOUT_OBJ = -1


DESCRIPTOR.enum_types_by_name['LayoutObjType'] = _LAYOUTOBJTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
