# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_messages_pb2 as edb__messages__pb2
import net_pb2 as net__pb2


class NetServiceStub(object):
  """Net service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/ansys.api.edb.v1.NetService/Create',
        request_serializer=net__pb2.NetCreationMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.FindByName = channel.unary_unary(
        '/ansys.api.edb.v1.NetService/FindByName',
        request_serializer=net__pb2.NetLookupMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )


class NetServiceServicer(object):
  """Net service definition
  """

  def Create(self, request, context):
    """Creates a net
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByName(self, request, context):
    """Finds a net on a layer by name
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=net__pb2.NetCreationMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'FindByName': grpc.unary_unary_rpc_method_handler(
          servicer.FindByName,
          request_deserializer=net__pb2.NetLookupMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.NetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
