# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: net.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='net.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tnet.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"S\n\x12NetCreationMessage\x12/\n\x06layout\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x0c\n\x04name\x18\x02 \x01(\t\"Q\n\x10NetLookupMessage\x12/\n\x06layout\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x0c\n\x04name\x18\x02 \x01(\t2\xb4\x01\n\nNetService\x12Q\n\x06\x43reate\x12$.ansys.api.edb.v1.NetCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12S\n\nFindByName\x12\".ansys.api.edb.v1.NetLookupMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])




_NETCREATIONMESSAGE = _descriptor.Descriptor(
  name='NetCreationMessage',
  full_name='ansys.api.edb.v1.NetCreationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='ansys.api.edb.v1.NetCreationMessage.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.NetCreationMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=134,
)


_NETLOOKUPMESSAGE = _descriptor.Descriptor(
  name='NetLookupMessage',
  full_name='ansys.api.edb.v1.NetLookupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='ansys.api.edb.v1.NetLookupMessage.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.NetLookupMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=217,
)

_NETCREATIONMESSAGE.fields_by_name['layout'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_NETLOOKUPMESSAGE.fields_by_name['layout'].message_type = edb__messages__pb2._EDBOBJMESSAGE
DESCRIPTOR.message_types_by_name['NetCreationMessage'] = _NETCREATIONMESSAGE
DESCRIPTOR.message_types_by_name['NetLookupMessage'] = _NETLOOKUPMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetCreationMessage = _reflection.GeneratedProtocolMessageType('NetCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _NETCREATIONMESSAGE,
  '__module__' : 'net_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.NetCreationMessage)
  })
_sym_db.RegisterMessage(NetCreationMessage)

NetLookupMessage = _reflection.GeneratedProtocolMessageType('NetLookupMessage', (_message.Message,), {
  'DESCRIPTOR' : _NETLOOKUPMESSAGE,
  '__module__' : 'net_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.NetLookupMessage)
  })
_sym_db.RegisterMessage(NetLookupMessage)



_NETSERVICE = _descriptor.ServiceDescriptor(
  name='NetService',
  full_name='ansys.api.edb.v1.NetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=220,
  serialized_end=400,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.NetService.Create',
    index=0,
    containing_service=None,
    input_type=_NETCREATIONMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindByName',
    full_name='ansys.api.edb.v1.NetService.FindByName',
    index=1,
    containing_service=None,
    input_type=_NETLOOKUPMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETSERVICE)

DESCRIPTOR.services_by_name['NetService'] = _NETSERVICE

# @@protoc_insertion_point(module_scope)
