# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2
import point_data_pb2 as point__data__pb2
import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='path.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npath.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\x1a\x10point_data.proto\x1a\nrefs.proto\"\xa3\x03\n\x13PathCreationMessage\x12/\n\x06layout\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x30\n\x05layer\x18\x02 \x01(\x0b\x32!.ansys.api.edb.v1.LayerRefMessage\x12,\n\x03net\x18\x03 \x01(\x0b\x32\x1f.ansys.api.edb.v1.NetRefMessage\x12-\n\x05width\x18\x04 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12\x33\n\x08\x65nd_cap1\x18\x05 \x01(\x0e\x32!.ansys.api.edb.v1.PathEndCapStyle\x12\x33\n\x08\x65nd_cap2\x18\x06 \x01(\x0e\x32!.ansys.api.edb.v1.PathEndCapStyle\x12\x31\n\x06\x63orner\x18\x07 \x01(\x0e\x32!.ansys.api.edb.v1.PathCornerStyle\x12/\n\x06points\x18\x08 \x01(\x0b\x32\x1f.ansys.api.edb.v1.PointsMessage*_\n\x0fPathEndCapStyle\x12\t\n\x05ROUND\x10\x00\x12\x08\n\x04\x46LAT\x10\x01\x12\x0c\n\x08\x45XTENDED\x10\x02\x12\x0b\n\x07\x43LIPPED\x10\x03\x12\x1c\n\x0fINVALID_END_CAP\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*G\n\x0fPathCornerStyle\x12\x10\n\x0cROUND_CORNER\x10\x00\x12\x10\n\x0cSHARP_CORNER\x10\x01\x12\x10\n\x0cMITER_CORNER\x10\x02\x32\x61\n\x0bPathService\x12R\n\x06\x43reate\x12%.ansys.api.edb.v1.PathCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,point__data__pb2.DESCRIPTOR,refs__pb2.DESCRIPTOR,])

_PATHENDCAPSTYLE = _descriptor.EnumDescriptor(
  name='PathEndCapStyle',
  full_name='ansys.api.edb.v1.PathEndCapStyle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROUND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTENDED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIPPED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_END_CAP', index=4, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=504,
  serialized_end=599,
)
_sym_db.RegisterEnumDescriptor(_PATHENDCAPSTYLE)

PathEndCapStyle = enum_type_wrapper.EnumTypeWrapper(_PATHENDCAPSTYLE)
_PATHCORNERSTYLE = _descriptor.EnumDescriptor(
  name='PathCornerStyle',
  full_name='ansys.api.edb.v1.PathCornerStyle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROUND_CORNER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARP_CORNER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MITER_CORNER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=601,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_PATHCORNERSTYLE)

PathCornerStyle = enum_type_wrapper.EnumTypeWrapper(_PATHCORNERSTYLE)
ROUND = 0
FLAT = 1
EXTENDED = 2
CLIPPED = 3
INVALID_END_CAP = -1
ROUND_CORNER = 0
SHARP_CORNER = 1
MITER_CORNER = 2



_PATHCREATIONMESSAGE = _descriptor.Descriptor(
  name='PathCreationMessage',
  full_name='ansys.api.edb.v1.PathCreationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='ansys.api.edb.v1.PathCreationMessage.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='ansys.api.edb.v1.PathCreationMessage.layer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net', full_name='ansys.api.edb.v1.PathCreationMessage.net', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='ansys.api.edb.v1.PathCreationMessage.width', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_cap1', full_name='ansys.api.edb.v1.PathCreationMessage.end_cap1', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_cap2', full_name='ansys.api.edb.v1.PathCreationMessage.end_cap2', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corner', full_name='ansys.api.edb.v1.PathCreationMessage.corner', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='ansys.api.edb.v1.PathCreationMessage.points', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=502,
)

_PATHCREATIONMESSAGE.fields_by_name['layout'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_PATHCREATIONMESSAGE.fields_by_name['layer'].message_type = refs__pb2._LAYERREFMESSAGE
_PATHCREATIONMESSAGE.fields_by_name['net'].message_type = refs__pb2._NETREFMESSAGE
_PATHCREATIONMESSAGE.fields_by_name['width'].message_type = edb__messages__pb2._VALUEMESSAGE
_PATHCREATIONMESSAGE.fields_by_name['end_cap1'].enum_type = _PATHENDCAPSTYLE
_PATHCREATIONMESSAGE.fields_by_name['end_cap2'].enum_type = _PATHENDCAPSTYLE
_PATHCREATIONMESSAGE.fields_by_name['corner'].enum_type = _PATHCORNERSTYLE
_PATHCREATIONMESSAGE.fields_by_name['points'].message_type = point__data__pb2._POINTSMESSAGE
DESCRIPTOR.message_types_by_name['PathCreationMessage'] = _PATHCREATIONMESSAGE
DESCRIPTOR.enum_types_by_name['PathEndCapStyle'] = _PATHENDCAPSTYLE
DESCRIPTOR.enum_types_by_name['PathCornerStyle'] = _PATHCORNERSTYLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathCreationMessage = _reflection.GeneratedProtocolMessageType('PathCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _PATHCREATIONMESSAGE,
  '__module__' : 'path_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.PathCreationMessage)
  })
_sym_db.RegisterMessage(PathCreationMessage)



_PATHSERVICE = _descriptor.ServiceDescriptor(
  name='PathService',
  full_name='ansys.api.edb.v1.PathService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=674,
  serialized_end=771,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.PathService.Create',
    index=0,
    containing_service=None,
    input_type=_PATHCREATIONMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PATHSERVICE)

DESCRIPTOR.services_by_name['PathService'] = _PATHSERVICE

# @@protoc_insertion_point(module_scope)
