# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='point_data.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10point_data.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"d\n\x0cPointMessage\x12)\n\x01x\x18\x01 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\x12)\n\x01y\x18\x02 \x01(\x0b\x32\x1e.ansys.api.edb.v1.ValueMessage\"}\n\x11PathPointsMessage\x12,\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1e.ansys.api.edb.v1.PointMessage\x12\x0e\n\x06\x63losed\x18\x02 \x01(\x08\x12*\n\x05sense\x18\x03 \x01(\x0e\x32\x1b.ansys.api.edb.v1.PolySense\"\x8d\x01\n\rPointsMessage\x12:\n\x0bpoints_data\x18\x01 \x01(\x0b\x32#.ansys.api.edb.v1.PathPointsMessageH\x00\x12\x37\n\x0cpolygon_data\x18\x02 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessageH\x00\x42\x07\n\x05shape*;\n\tPolySense\x12\x11\n\rSENSE_UNKNOWN\x10\x00\x12\x0c\n\x08SENSE_CW\x10\x01\x12\r\n\tSENSE_CCW\x10\x02\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])

_POLYSENSE = _descriptor.EnumDescriptor(
  name='PolySense',
  full_name='ansys.api.edb.v1.PolySense',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SENSE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSE_CW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSE_CCW', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=431,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_POLYSENSE)

PolySense = enum_type_wrapper.EnumTypeWrapper(_POLYSENSE)
SENSE_UNKNOWN = 0
SENSE_CW = 1
SENSE_CCW = 2



_POINTMESSAGE = _descriptor.Descriptor(
  name='PointMessage',
  full_name='ansys.api.edb.v1.PointMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ansys.api.edb.v1.PointMessage.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ansys.api.edb.v1.PointMessage.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=158,
)


_PATHPOINTSMESSAGE = _descriptor.Descriptor(
  name='PathPointsMessage',
  full_name='ansys.api.edb.v1.PathPointsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ansys.api.edb.v1.PathPointsMessage.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closed', full_name='ansys.api.edb.v1.PathPointsMessage.closed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sense', full_name='ansys.api.edb.v1.PathPointsMessage.sense', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=285,
)


_POINTSMESSAGE = _descriptor.Descriptor(
  name='PointsMessage',
  full_name='ansys.api.edb.v1.PointsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points_data', full_name='ansys.api.edb.v1.PointsMessage.points_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='polygon_data', full_name='ansys.api.edb.v1.PointsMessage.polygon_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='shape', full_name='ansys.api.edb.v1.PointsMessage.shape',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=288,
  serialized_end=429,
)

_POINTMESSAGE.fields_by_name['x'].message_type = edb__messages__pb2._VALUEMESSAGE
_POINTMESSAGE.fields_by_name['y'].message_type = edb__messages__pb2._VALUEMESSAGE
_PATHPOINTSMESSAGE.fields_by_name['data'].message_type = _POINTMESSAGE
_PATHPOINTSMESSAGE.fields_by_name['sense'].enum_type = _POLYSENSE
_POINTSMESSAGE.fields_by_name['points_data'].message_type = _PATHPOINTSMESSAGE
_POINTSMESSAGE.fields_by_name['polygon_data'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_POINTSMESSAGE.oneofs_by_name['shape'].fields.append(
  _POINTSMESSAGE.fields_by_name['points_data'])
_POINTSMESSAGE.fields_by_name['points_data'].containing_oneof = _POINTSMESSAGE.oneofs_by_name['shape']
_POINTSMESSAGE.oneofs_by_name['shape'].fields.append(
  _POINTSMESSAGE.fields_by_name['polygon_data'])
_POINTSMESSAGE.fields_by_name['polygon_data'].containing_oneof = _POINTSMESSAGE.oneofs_by_name['shape']
DESCRIPTOR.message_types_by_name['PointMessage'] = _POINTMESSAGE
DESCRIPTOR.message_types_by_name['PathPointsMessage'] = _PATHPOINTSMESSAGE
DESCRIPTOR.message_types_by_name['PointsMessage'] = _POINTSMESSAGE
DESCRIPTOR.enum_types_by_name['PolySense'] = _POLYSENSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointMessage = _reflection.GeneratedProtocolMessageType('PointMessage', (_message.Message,), {
  'DESCRIPTOR' : _POINTMESSAGE,
  '__module__' : 'point_data_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.PointMessage)
  })
_sym_db.RegisterMessage(PointMessage)

PathPointsMessage = _reflection.GeneratedProtocolMessageType('PathPointsMessage', (_message.Message,), {
  'DESCRIPTOR' : _PATHPOINTSMESSAGE,
  '__module__' : 'point_data_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.PathPointsMessage)
  })
_sym_db.RegisterMessage(PathPointsMessage)

PointsMessage = _reflection.GeneratedProtocolMessageType('PointsMessage', (_message.Message,), {
  'DESCRIPTOR' : _POINTSMESSAGE,
  '__module__' : 'point_data_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.PointsMessage)
  })
_sym_db.RegisterMessage(PointsMessage)


# @@protoc_insertion_point(module_scope)
