# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polygon_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2
import point_data_pb2 as point__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='polygon_data.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12polygon_data.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\x1a\x10point_data.proto2\xac\x01\n\x12PolygonDataService\x12P\n\x06\x43reate\x12#.ansys.api.edb.v1.PathPointsMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12\x44\n\x07\x43leanup\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,point__data__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_POLYGONDATASERVICE = _descriptor.ServiceDescriptor(
  name='PolygonDataService',
  full_name='ansys.api.edb.v1.PolygonDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.PolygonDataService.Create',
    index=0,
    containing_service=None,
    input_type=point__data__pb2._PATHPOINTSMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Cleanup',
    full_name='ansys.api.edb.v1.PolygonDataService.Cleanup',
    index=1,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLYGONDATASERVICE)

DESCRIPTOR.services_by_name['PolygonDataService'] = _POLYGONDATASERVICE

# @@protoc_insertion_point(module_scope)
