# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import point_data_pb2 as point__data__pb2


class PolygonDataServiceStub(object):
  """Polygon Data service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/ansys.api.edb.v1.PolygonDataService/Create',
        request_serializer=point__data__pb2.PathPointsMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.Cleanup = channel.unary_unary(
        '/ansys.api.edb.v1.PolygonDataService/Cleanup',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class PolygonDataServiceServicer(object):
  """Polygon Data service definition
  """

  def Create(self, request, context):
    """Creates a polygon data from array of points and polygon options
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Cleanup(self, request, context):
    """Destroy a polygon Data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PolygonDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=point__data__pb2.PathPointsMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'Cleanup': grpc.unary_unary_rpc_method_handler(
          servicer.Cleanup,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.PolygonDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
