# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_iterator_pb2 as edb__iterator__pb2
import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import primitive_pb2 as primitive__pb2


class PrimitiveServiceStub(object):
  """Primitive service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPrimitiveType = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/GetPrimitiveType',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=primitive__pb2.PrimitiveTypeMessage.FromString,
        )
    self.AddVoid = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/AddVoid',
        request_serializer=primitive__pb2.PrimitiveVoidCreationMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.SetHfssProp = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/SetHfssProp',
        request_serializer=primitive__pb2.PrimitiveHfssPropMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.GetLayer = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/GetLayer',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.SetLayer = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/SetLayer',
        request_serializer=primitive__pb2.SetLayerMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.GetIsNegative = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/GetIsNegative',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.SetIsNegative = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/SetIsNegative',
        request_serializer=primitive__pb2.SetIsNegativeMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.IsVoid = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/IsVoid',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.HasVoids = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/HasVoids',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.Voids = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/Voids',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__iterator__pb2.EDBIteratorMessage.FromString,
        )
    self.GetOwner = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/GetOwner',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.IsParameterized = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/IsParameterized',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.GetHfssProp = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/GetHfssProp',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=primitive__pb2.GetPrimitiveHfssPropMessage.FromString,
        )
    self.RemoveHfssProp = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/RemoveHfssProp',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.IsZonePrimitive = channel.unary_unary(
        '/ansys.api.edb.v1.PrimitiveService/IsZonePrimitive',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )


class PrimitiveServiceServicer(object):
  """Primitive service definition
  """

  def GetPrimitiveType(self, request, context):
    """Gets the primitive type of this primitive
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddVoid(self, request, context):
    """Adds a void
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetHfssProp(self, request, context):
    """Sets HFSS Properties
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLayer(self, request, context):
    """Get Layer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLayer(self, request, context):
    """Set Layer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIsNegative(self, request, context):
    """Get IsNegative
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetIsNegative(self, request, context):
    """Set IsNegative
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsVoid(self, request, context):
    """Get isVoid
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasVoids(self, request, context):
    """Get HasVoids
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Voids(self, request, context):
    """Gets an iterator of the voids in the Primitive
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOwner(self, request, context):
    """Get Owner
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsParameterized(self, request, context):
    """Get isParametrized
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHfssProp(self, request, context):
    """Get HFSS Properties
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveHfssProp(self, request, context):
    """Remove HFSS Properties
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsZonePrimitive(self, request, context):
    """Get Is Zone Primitive
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrimitiveServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPrimitiveType': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrimitiveType,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=primitive__pb2.PrimitiveTypeMessage.SerializeToString,
      ),
      'AddVoid': grpc.unary_unary_rpc_method_handler(
          servicer.AddVoid,
          request_deserializer=primitive__pb2.PrimitiveVoidCreationMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'SetHfssProp': grpc.unary_unary_rpc_method_handler(
          servicer.SetHfssProp,
          request_deserializer=primitive__pb2.PrimitiveHfssPropMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'GetLayer': grpc.unary_unary_rpc_method_handler(
          servicer.GetLayer,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'SetLayer': grpc.unary_unary_rpc_method_handler(
          servicer.SetLayer,
          request_deserializer=primitive__pb2.SetLayerMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'GetIsNegative': grpc.unary_unary_rpc_method_handler(
          servicer.GetIsNegative,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'SetIsNegative': grpc.unary_unary_rpc_method_handler(
          servicer.SetIsNegative,
          request_deserializer=primitive__pb2.SetIsNegativeMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'IsVoid': grpc.unary_unary_rpc_method_handler(
          servicer.IsVoid,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'HasVoids': grpc.unary_unary_rpc_method_handler(
          servicer.HasVoids,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'Voids': grpc.unary_unary_rpc_method_handler(
          servicer.Voids,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__iterator__pb2.EDBIteratorMessage.SerializeToString,
      ),
      'GetOwner': grpc.unary_unary_rpc_method_handler(
          servicer.GetOwner,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'IsParameterized': grpc.unary_unary_rpc_method_handler(
          servicer.IsParameterized,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'GetHfssProp': grpc.unary_unary_rpc_method_handler(
          servicer.GetHfssProp,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=primitive__pb2.GetPrimitiveHfssPropMessage.SerializeToString,
      ),
      'RemoveHfssProp': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveHfssProp,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'IsZonePrimitive': grpc.unary_unary_rpc_method_handler(
          servicer.IsZonePrimitive,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.PrimitiveService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
