# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: refs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='refs.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nrefs.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"u\n\x0fLayerRefMessage\x12-\n\x02id\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessageH\x00\x12,\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x42\x05\n\x03ref\"s\n\rNetRefMessage\x12-\n\x02id\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessageH\x00\x12,\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x42\x05\n\x03refb\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])




_LAYERREFMESSAGE = _descriptor.Descriptor(
  name='LayerRefMessage',
  full_name='ansys.api.edb.v1.LayerRefMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ansys.api.edb.v1.LayerRefMessage.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.LayerRefMessage.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ref', full_name='ansys.api.edb.v1.LayerRefMessage.ref',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=52,
  serialized_end=169,
)


_NETREFMESSAGE = _descriptor.Descriptor(
  name='NetRefMessage',
  full_name='ansys.api.edb.v1.NetRefMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ansys.api.edb.v1.NetRefMessage.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.NetRefMessage.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ref', full_name='ansys.api.edb.v1.NetRefMessage.ref',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=171,
  serialized_end=286,
)

_LAYERREFMESSAGE.fields_by_name['id'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_LAYERREFMESSAGE.fields_by_name['name'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_LAYERREFMESSAGE.oneofs_by_name['ref'].fields.append(
  _LAYERREFMESSAGE.fields_by_name['id'])
_LAYERREFMESSAGE.fields_by_name['id'].containing_oneof = _LAYERREFMESSAGE.oneofs_by_name['ref']
_LAYERREFMESSAGE.oneofs_by_name['ref'].fields.append(
  _LAYERREFMESSAGE.fields_by_name['name'])
_LAYERREFMESSAGE.fields_by_name['name'].containing_oneof = _LAYERREFMESSAGE.oneofs_by_name['ref']
_NETREFMESSAGE.fields_by_name['id'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_NETREFMESSAGE.fields_by_name['name'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_NETREFMESSAGE.oneofs_by_name['ref'].fields.append(
  _NETREFMESSAGE.fields_by_name['id'])
_NETREFMESSAGE.fields_by_name['id'].containing_oneof = _NETREFMESSAGE.oneofs_by_name['ref']
_NETREFMESSAGE.oneofs_by_name['ref'].fields.append(
  _NETREFMESSAGE.fields_by_name['name'])
_NETREFMESSAGE.fields_by_name['name'].containing_oneof = _NETREFMESSAGE.oneofs_by_name['ref']
DESCRIPTOR.message_types_by_name['LayerRefMessage'] = _LAYERREFMESSAGE
DESCRIPTOR.message_types_by_name['NetRefMessage'] = _NETREFMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerRefMessage = _reflection.GeneratedProtocolMessageType('LayerRefMessage', (_message.Message,), {
  'DESCRIPTOR' : _LAYERREFMESSAGE,
  '__module__' : 'refs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.LayerRefMessage)
  })
_sym_db.RegisterMessage(LayerRefMessage)

NetRefMessage = _reflection.GeneratedProtocolMessageType('NetRefMessage', (_message.Message,), {
  'DESCRIPTOR' : _NETREFMESSAGE,
  '__module__' : 'refs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.NetRefMessage)
  })
_sym_db.RegisterMessage(NetRefMessage)


# @@protoc_insertion_point(module_scope)
