# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import simulation_setup_pb2 as simulation__setup__pb2


class SimulationSetupServiceStub(object):
  """SimulationSetup service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/ansys.api.edb.v1.SimulationSetupService/Create',
        request_serializer=simulation__setup__pb2.SimulationSetupCreationMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.GetSimulationSetupInfo = channel.unary_unary(
        '/ansys.api.edb.v1.SimulationSetupService/GetSimulationSetupInfo',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.AddAdaptiveFrequencies = channel.unary_unary(
        '/ansys.api.edb.v1.SimulationSetupService/AddAdaptiveFrequencies',
        request_serializer=simulation__setup__pb2.AdaptiveFrequenciesSetMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.AddMeshOperations = channel.unary_unary(
        '/ansys.api.edb.v1.SimulationSetupService/AddMeshOperations',
        request_serializer=simulation__setup__pb2.MeshOperationsSetMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.AddFrequencySweeps = channel.unary_unary(
        '/ansys.api.edb.v1.SimulationSetupService/AddFrequencySweeps',
        request_serializer=simulation__setup__pb2.FrequencySweepsSetMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )


class SimulationSetupServiceServicer(object):
  """SimulationSetup service definition
  """

  def Create(self, request, context):
    """Creates a SimulationSetup in the given cell with the provided type and name
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSimulationSetupInfo(self, request, context):
    """Get the SimSetupInfo of the SimulationSetup
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddAdaptiveFrequencies(self, request, context):
    """Add adaptive frequency
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMeshOperations(self, request, context):
    """Add mesh operations
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddFrequencySweeps(self, request, context):
    """Add frequency sweeps
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimulationSetupServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=simulation__setup__pb2.SimulationSetupCreationMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'GetSimulationSetupInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetSimulationSetupInfo,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'AddAdaptiveFrequencies': grpc.unary_unary_rpc_method_handler(
          servicer.AddAdaptiveFrequencies,
          request_deserializer=simulation__setup__pb2.AdaptiveFrequenciesSetMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'AddMeshOperations': grpc.unary_unary_rpc_method_handler(
          servicer.AddMeshOperations,
          request_deserializer=simulation__setup__pb2.MeshOperationsSetMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'AddFrequencySweeps': grpc.unary_unary_rpc_method_handler(
          servicer.AddFrequencySweeps,
          request_deserializer=simulation__setup__pb2.FrequencySweepsSetMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.SimulationSetupService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
