# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation_setup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2
import adaptive_settings_pb2 as adaptive__settings__pb2
import simulation_setup_info_pb2 as simulation__setup__info__pb2
import simulation_settings_pb2 as simulation__settings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation_setup.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16simulation_setup.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\x1a\x17\x61\x64\x61ptive_settings.proto\x1a\x1bsimulation_setup_info.proto\x1a\x19simulation_settings.proto\"\xb4\x01\n\x1eSimulationSetupCreationMessage\x12-\n\x04\x63\x65ll\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x1d\n\x15simulation_setup_name\x18\x02 \x01(\t\x12\x44\n\x15simulation_setup_type\x18\x03 \x01(\x0e\x32%.ansys.api.edb.v1.SimulationSetupType\"\x94\x01\n\x1d\x41\x64\x61ptiveFrequenciesSetMessage\x12.\n\x05setup\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x43\n\x0b\x66requencies\x18\x02 \x03(\x0b\x32..ansys.api.edb.v1.AdaptiveFrequencyDataMessage\"\x8b\x01\n\x18MeshOperationsSetMessage\x12.\n\x05setup\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12?\n\x0fmesh_operations\x18\x02 \x03(\x0b\x32&.ansys.api.edb.v1.MeshOperationMessage\"\x7f\n\x19\x46requencySweepsSetMessage\x12.\n\x05setup\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x32\n\x06sweeps\x18\x02 \x03(\x0b\x32\".ansys.api.edb.v1.SweepDataMessage*\x1f\n\x13SimulationSetupType\x12\x08\n\x04HFSS\x10\x00\x32\xfe\x03\n\x16SimulationSetupService\x12]\n\x06\x43reate\x12\x30.ansys.api.edb.v1.SimulationSetupCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12\\\n\x16GetSimulationSetupInfo\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12g\n\x16\x41\x64\x64\x41\x64\x61ptiveFrequencies\x12/.ansys.api.edb.v1.AdaptiveFrequenciesSetMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12]\n\x11\x41\x64\x64MeshOperations\x12*.ansys.api.edb.v1.MeshOperationsSetMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x12_\n\x12\x41\x64\x64\x46requencySweeps\x12+.ansys.api.edb.v1.FrequencySweepsSetMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,adaptive__settings__pb2.DESCRIPTOR,simulation__setup__info__pb2.DESCRIPTOR,simulation__settings__pb2.DESCRIPTOR,])

_SIMULATIONSETUPTYPE = _descriptor.EnumDescriptor(
  name='SimulationSetupType',
  full_name='ansys.api.edb.v1.SimulationSetupType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HFSS', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=750,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONSETUPTYPE)

SimulationSetupType = enum_type_wrapper.EnumTypeWrapper(_SIMULATIONSETUPTYPE)
HFSS = 0



_SIMULATIONSETUPCREATIONMESSAGE = _descriptor.Descriptor(
  name='SimulationSetupCreationMessage',
  full_name='ansys.api.edb.v1.SimulationSetupCreationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell', full_name='ansys.api.edb.v1.SimulationSetupCreationMessage.cell', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simulation_setup_name', full_name='ansys.api.edb.v1.SimulationSetupCreationMessage.simulation_setup_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simulation_setup_type', full_name='ansys.api.edb.v1.SimulationSetupCreationMessage.simulation_setup_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=326,
)


_ADAPTIVEFREQUENCIESSETMESSAGE = _descriptor.Descriptor(
  name='AdaptiveFrequenciesSetMessage',
  full_name='ansys.api.edb.v1.AdaptiveFrequenciesSetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup', full_name='ansys.api.edb.v1.AdaptiveFrequenciesSetMessage.setup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequencies', full_name='ansys.api.edb.v1.AdaptiveFrequenciesSetMessage.frequencies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=477,
)


_MESHOPERATIONSSETMESSAGE = _descriptor.Descriptor(
  name='MeshOperationsSetMessage',
  full_name='ansys.api.edb.v1.MeshOperationsSetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup', full_name='ansys.api.edb.v1.MeshOperationsSetMessage.setup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh_operations', full_name='ansys.api.edb.v1.MeshOperationsSetMessage.mesh_operations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=619,
)


_FREQUENCYSWEEPSSETMESSAGE = _descriptor.Descriptor(
  name='FrequencySweepsSetMessage',
  full_name='ansys.api.edb.v1.FrequencySweepsSetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup', full_name='ansys.api.edb.v1.FrequencySweepsSetMessage.setup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sweeps', full_name='ansys.api.edb.v1.FrequencySweepsSetMessage.sweeps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=748,
)

_SIMULATIONSETUPCREATIONMESSAGE.fields_by_name['cell'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_SIMULATIONSETUPCREATIONMESSAGE.fields_by_name['simulation_setup_type'].enum_type = _SIMULATIONSETUPTYPE
_ADAPTIVEFREQUENCIESSETMESSAGE.fields_by_name['setup'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_ADAPTIVEFREQUENCIESSETMESSAGE.fields_by_name['frequencies'].message_type = adaptive__settings__pb2._ADAPTIVEFREQUENCYDATAMESSAGE
_MESHOPERATIONSSETMESSAGE.fields_by_name['setup'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_MESHOPERATIONSSETMESSAGE.fields_by_name['mesh_operations'].message_type = simulation__settings__pb2._MESHOPERATIONMESSAGE
_FREQUENCYSWEEPSSETMESSAGE.fields_by_name['setup'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_FREQUENCYSWEEPSSETMESSAGE.fields_by_name['sweeps'].message_type = simulation__setup__info__pb2._SWEEPDATAMESSAGE
DESCRIPTOR.message_types_by_name['SimulationSetupCreationMessage'] = _SIMULATIONSETUPCREATIONMESSAGE
DESCRIPTOR.message_types_by_name['AdaptiveFrequenciesSetMessage'] = _ADAPTIVEFREQUENCIESSETMESSAGE
DESCRIPTOR.message_types_by_name['MeshOperationsSetMessage'] = _MESHOPERATIONSSETMESSAGE
DESCRIPTOR.message_types_by_name['FrequencySweepsSetMessage'] = _FREQUENCYSWEEPSSETMESSAGE
DESCRIPTOR.enum_types_by_name['SimulationSetupType'] = _SIMULATIONSETUPTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationSetupCreationMessage = _reflection.GeneratedProtocolMessageType('SimulationSetupCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONSETUPCREATIONMESSAGE,
  '__module__' : 'simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SimulationSetupCreationMessage)
  })
_sym_db.RegisterMessage(SimulationSetupCreationMessage)

AdaptiveFrequenciesSetMessage = _reflection.GeneratedProtocolMessageType('AdaptiveFrequenciesSetMessage', (_message.Message,), {
  'DESCRIPTOR' : _ADAPTIVEFREQUENCIESSETMESSAGE,
  '__module__' : 'simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.AdaptiveFrequenciesSetMessage)
  })
_sym_db.RegisterMessage(AdaptiveFrequenciesSetMessage)

MeshOperationsSetMessage = _reflection.GeneratedProtocolMessageType('MeshOperationsSetMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONSSETMESSAGE,
  '__module__' : 'simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationsSetMessage)
  })
_sym_db.RegisterMessage(MeshOperationsSetMessage)

FrequencySweepsSetMessage = _reflection.GeneratedProtocolMessageType('FrequencySweepsSetMessage', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYSWEEPSSETMESSAGE,
  '__module__' : 'simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.FrequencySweepsSetMessage)
  })
_sym_db.RegisterMessage(FrequencySweepsSetMessage)



_SIMULATIONSETUPSERVICE = _descriptor.ServiceDescriptor(
  name='SimulationSetupService',
  full_name='ansys.api.edb.v1.SimulationSetupService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=784,
  serialized_end=1294,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.SimulationSetupService.Create',
    index=0,
    containing_service=None,
    input_type=_SIMULATIONSETUPCREATIONMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSimulationSetupInfo',
    full_name='ansys.api.edb.v1.SimulationSetupService.GetSimulationSetupInfo',
    index=1,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddAdaptiveFrequencies',
    full_name='ansys.api.edb.v1.SimulationSetupService.AddAdaptiveFrequencies',
    index=2,
    containing_service=None,
    input_type=_ADAPTIVEFREQUENCIESSETMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddMeshOperations',
    full_name='ansys.api.edb.v1.SimulationSetupService.AddMeshOperations',
    index=3,
    containing_service=None,
    input_type=_MESHOPERATIONSSETMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddFrequencySweeps',
    full_name='ansys.api.edb.v1.SimulationSetupService.AddFrequencySweeps',
    index=4,
    containing_service=None,
    input_type=_FREQUENCYSWEEPSSETMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATIONSETUPSERVICE)

DESCRIPTOR.services_by_name['SimulationSetupService'] = _SIMULATIONSETUPSERVICE

# @@protoc_insertion_point(module_scope)
