# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation_settings.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19simulation_settings.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"I\n\x19MeshOpNetLayerInfoMessage\x12\x0b\n\x03net\x18\x01 \x01(\t\x12\r\n\x05layer\x18\x02 \x01(\t\x12\x10\n\x08is_sheet\x18\x03 \x01(\x08\"\xa1\x01\n\x1dSkinDepthMeshOperationMessage\x12\x12\n\nskin_depth\x18\x01 \x01(\t\x12#\n\x1bmax_surface_triangle_length\x18\x02 \x01(\t\x12\x12\n\nnum_layers\x18\x03 \x01(\t\x12\x14\n\x0cmax_elements\x18\x04 \x01(\t\x12\x1d\n\x15restrict_max_elements\x18\x05 \x01(\x08\"\x90\x02\n\x14MeshOperationMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x15\n\rrefine_inside\x18\x03 \x01(\x08\x12\x13\n\x0bmesh_region\x18\x04 \x01(\t\x12\x43\n\x0enet_layer_info\x18\x05 \x03(\x0b\x32+.ansys.api.edb.v1.MeshOpNetLayerInfoMessage\x12M\n\x12skin_depth_mesh_op\x18\x06 \x01(\x0b\x32/.ansys.api.edb.v1.SkinDepthMeshOperationMessageH\x00\x42\x19\n\x17mesh_operation_sub_type\"X\n\x15MeshOperationsMessage\x12?\n\x0fmesh_operations\x18\x01 \x03(\x0b\x32&.ansys.api.edb.v1.MeshOperationMessage\"\x9f\x01\n\x18SetMeshOperationsMessage\x12\x41\n\x18hfss_simulation_settings\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12@\n\x0fmesh_operations\x18\x02 \x01(\x0b\x32\'.ansys.api.edb.v1.MeshOperationsMessage*q\n\x11MeshOperationType\x12\x13\n\x0fMESH_SETUP_BASE\x10\x00\x12\x15\n\x11MESH_SETUP_LENGTH\x10\x01\x12\x19\n\x15MESH_SETUP_SKIN_DEPTH\x10\x02\x12\x15\n\x11NUM_MESH_OP_TYPES\x10\x03\x32\xd4\x01\n\x1cHFSSSimulatonSettingsService\x12Y\n\x13GetAdaptiveSettings\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12Y\n\x11SetMeshOperations\x12*.ansys.api.edb.v1.SetMeshOperationsMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])

_MESHOPERATIONTYPE = _descriptor.EnumDescriptor(
  name='MeshOperationType',
  full_name='ansys.api.edb.v1.MeshOperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MESH_SETUP_BASE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESH_SETUP_LENGTH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESH_SETUP_SKIN_DEPTH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUM_MESH_OP_TYPES', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=833,
  serialized_end=946,
)
_sym_db.RegisterEnumDescriptor(_MESHOPERATIONTYPE)

MeshOperationType = enum_type_wrapper.EnumTypeWrapper(_MESHOPERATIONTYPE)
MESH_SETUP_BASE = 0
MESH_SETUP_LENGTH = 1
MESH_SETUP_SKIN_DEPTH = 2
NUM_MESH_OP_TYPES = 3



_MESHOPNETLAYERINFOMESSAGE = _descriptor.Descriptor(
  name='MeshOpNetLayerInfoMessage',
  full_name='ansys.api.edb.v1.MeshOpNetLayerInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='ansys.api.edb.v1.MeshOpNetLayerInfoMessage.net', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='ansys.api.edb.v1.MeshOpNetLayerInfoMessage.layer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_sheet', full_name='ansys.api.edb.v1.MeshOpNetLayerInfoMessage.is_sheet', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=140,
)


_SKINDEPTHMESHOPERATIONMESSAGE = _descriptor.Descriptor(
  name='SkinDepthMeshOperationMessage',
  full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skin_depth', full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage.skin_depth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_surface_triangle_length', full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage.max_surface_triangle_length', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_layers', full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage.num_layers', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_elements', full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage.max_elements', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restrict_max_elements', full_name='ansys.api.edb.v1.SkinDepthMeshOperationMessage.restrict_max_elements', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=304,
)


_MESHOPERATIONMESSAGE = _descriptor.Descriptor(
  name='MeshOperationMessage',
  full_name='ansys.api.edb.v1.MeshOperationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.MeshOperationMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='ansys.api.edb.v1.MeshOperationMessage.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refine_inside', full_name='ansys.api.edb.v1.MeshOperationMessage.refine_inside', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh_region', full_name='ansys.api.edb.v1.MeshOperationMessage.mesh_region', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_layer_info', full_name='ansys.api.edb.v1.MeshOperationMessage.net_layer_info', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skin_depth_mesh_op', full_name='ansys.api.edb.v1.MeshOperationMessage.skin_depth_mesh_op', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='mesh_operation_sub_type', full_name='ansys.api.edb.v1.MeshOperationMessage.mesh_operation_sub_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=307,
  serialized_end=579,
)


_MESHOPERATIONSMESSAGE = _descriptor.Descriptor(
  name='MeshOperationsMessage',
  full_name='ansys.api.edb.v1.MeshOperationsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mesh_operations', full_name='ansys.api.edb.v1.MeshOperationsMessage.mesh_operations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=669,
)


_SETMESHOPERATIONSMESSAGE = _descriptor.Descriptor(
  name='SetMeshOperationsMessage',
  full_name='ansys.api.edb.v1.SetMeshOperationsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hfss_simulation_settings', full_name='ansys.api.edb.v1.SetMeshOperationsMessage.hfss_simulation_settings', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh_operations', full_name='ansys.api.edb.v1.SetMeshOperationsMessage.mesh_operations', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=831,
)

_MESHOPERATIONMESSAGE.fields_by_name['net_layer_info'].message_type = _MESHOPNETLAYERINFOMESSAGE
_MESHOPERATIONMESSAGE.fields_by_name['skin_depth_mesh_op'].message_type = _SKINDEPTHMESHOPERATIONMESSAGE
_MESHOPERATIONMESSAGE.oneofs_by_name['mesh_operation_sub_type'].fields.append(
  _MESHOPERATIONMESSAGE.fields_by_name['skin_depth_mesh_op'])
_MESHOPERATIONMESSAGE.fields_by_name['skin_depth_mesh_op'].containing_oneof = _MESHOPERATIONMESSAGE.oneofs_by_name['mesh_operation_sub_type']
_MESHOPERATIONSMESSAGE.fields_by_name['mesh_operations'].message_type = _MESHOPERATIONMESSAGE
_SETMESHOPERATIONSMESSAGE.fields_by_name['hfss_simulation_settings'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_SETMESHOPERATIONSMESSAGE.fields_by_name['mesh_operations'].message_type = _MESHOPERATIONSMESSAGE
DESCRIPTOR.message_types_by_name['MeshOpNetLayerInfoMessage'] = _MESHOPNETLAYERINFOMESSAGE
DESCRIPTOR.message_types_by_name['SkinDepthMeshOperationMessage'] = _SKINDEPTHMESHOPERATIONMESSAGE
DESCRIPTOR.message_types_by_name['MeshOperationMessage'] = _MESHOPERATIONMESSAGE
DESCRIPTOR.message_types_by_name['MeshOperationsMessage'] = _MESHOPERATIONSMESSAGE
DESCRIPTOR.message_types_by_name['SetMeshOperationsMessage'] = _SETMESHOPERATIONSMESSAGE
DESCRIPTOR.enum_types_by_name['MeshOperationType'] = _MESHOPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeshOpNetLayerInfoMessage = _reflection.GeneratedProtocolMessageType('MeshOpNetLayerInfoMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPNETLAYERINFOMESSAGE,
  '__module__' : 'simulation_settings_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOpNetLayerInfoMessage)
  })
_sym_db.RegisterMessage(MeshOpNetLayerInfoMessage)

SkinDepthMeshOperationMessage = _reflection.GeneratedProtocolMessageType('SkinDepthMeshOperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _SKINDEPTHMESHOPERATIONMESSAGE,
  '__module__' : 'simulation_settings_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SkinDepthMeshOperationMessage)
  })
_sym_db.RegisterMessage(SkinDepthMeshOperationMessage)

MeshOperationMessage = _reflection.GeneratedProtocolMessageType('MeshOperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONMESSAGE,
  '__module__' : 'simulation_settings_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationMessage)
  })
_sym_db.RegisterMessage(MeshOperationMessage)

MeshOperationsMessage = _reflection.GeneratedProtocolMessageType('MeshOperationsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONSMESSAGE,
  '__module__' : 'simulation_settings_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationsMessage)
  })
_sym_db.RegisterMessage(MeshOperationsMessage)

SetMeshOperationsMessage = _reflection.GeneratedProtocolMessageType('SetMeshOperationsMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETMESHOPERATIONSMESSAGE,
  '__module__' : 'simulation_settings_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SetMeshOperationsMessage)
  })
_sym_db.RegisterMessage(SetMeshOperationsMessage)



_HFSSSIMULATONSETTINGSSERVICE = _descriptor.ServiceDescriptor(
  name='HFSSSimulatonSettingsService',
  full_name='ansys.api.edb.v1.HFSSSimulatonSettingsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=949,
  serialized_end=1161,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAdaptiveSettings',
    full_name='ansys.api.edb.v1.HFSSSimulatonSettingsService.GetAdaptiveSettings',
    index=0,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetMeshOperations',
    full_name='ansys.api.edb.v1.HFSSSimulatonSettingsService.SetMeshOperations',
    index=1,
    containing_service=None,
    input_type=_SETMESHOPERATIONSMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HFSSSIMULATONSETTINGSSERVICE)

DESCRIPTOR.services_by_name['HFSSSimulatonSettingsService'] = _HFSSSIMULATONSETTINGSSERVICE

# @@protoc_insertion_point(module_scope)
