# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation_setup_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation_setup_info.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bsimulation_setup_info.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"N\n\x10SweepDataMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x66requency_string\x18\x02 \x01(\t\x12\x12\n\nfast_sweep\x18\x03 \x01(\x08\"N\n\x14SweepDataListMessage\x12\x36\n\nsweep_data\x18\x01 \x03(\x0b\x32\".ansys.api.edb.v1.SweepDataMessage\"\x9a\x01\n\x17SetSweepDataListMessage\x12>\n\x15simulation_setup_info\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12?\n\x0fsweep_data_list\x18\x02 \x01(\x0b\x32&.ansys.api.edb.v1.SweepDataListMessage2\xb1\x02\n\x1aSimulationSetupInfoService\x12[\n\x15GetSimulationSettings\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12]\n\x10GetSweepDataList\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a&.ansys.api.edb.v1.SweepDataListMessage\"\x00\x12W\n\x10SetSweepDataList\x12).ansys.api.edb.v1.SetSweepDataListMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])




_SWEEPDATAMESSAGE = _descriptor.Descriptor(
  name='SweepDataMessage',
  full_name='ansys.api.edb.v1.SweepDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.edb.v1.SweepDataMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency_string', full_name='ansys.api.edb.v1.SweepDataMessage.frequency_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fast_sweep', full_name='ansys.api.edb.v1.SweepDataMessage.fast_sweep', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=147,
)


_SWEEPDATALISTMESSAGE = _descriptor.Descriptor(
  name='SweepDataListMessage',
  full_name='ansys.api.edb.v1.SweepDataListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sweep_data', full_name='ansys.api.edb.v1.SweepDataListMessage.sweep_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=227,
)


_SETSWEEPDATALISTMESSAGE = _descriptor.Descriptor(
  name='SetSweepDataListMessage',
  full_name='ansys.api.edb.v1.SetSweepDataListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simulation_setup_info', full_name='ansys.api.edb.v1.SetSweepDataListMessage.simulation_setup_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sweep_data_list', full_name='ansys.api.edb.v1.SetSweepDataListMessage.sweep_data_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=384,
)

_SWEEPDATALISTMESSAGE.fields_by_name['sweep_data'].message_type = _SWEEPDATAMESSAGE
_SETSWEEPDATALISTMESSAGE.fields_by_name['simulation_setup_info'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_SETSWEEPDATALISTMESSAGE.fields_by_name['sweep_data_list'].message_type = _SWEEPDATALISTMESSAGE
DESCRIPTOR.message_types_by_name['SweepDataMessage'] = _SWEEPDATAMESSAGE
DESCRIPTOR.message_types_by_name['SweepDataListMessage'] = _SWEEPDATALISTMESSAGE
DESCRIPTOR.message_types_by_name['SetSweepDataListMessage'] = _SETSWEEPDATALISTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SweepDataMessage = _reflection.GeneratedProtocolMessageType('SweepDataMessage', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPDATAMESSAGE,
  '__module__' : 'simulation_setup_info_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SweepDataMessage)
  })
_sym_db.RegisterMessage(SweepDataMessage)

SweepDataListMessage = _reflection.GeneratedProtocolMessageType('SweepDataListMessage', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPDATALISTMESSAGE,
  '__module__' : 'simulation_setup_info_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SweepDataListMessage)
  })
_sym_db.RegisterMessage(SweepDataListMessage)

SetSweepDataListMessage = _reflection.GeneratedProtocolMessageType('SetSweepDataListMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETSWEEPDATALISTMESSAGE,
  '__module__' : 'simulation_setup_info_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SetSweepDataListMessage)
  })
_sym_db.RegisterMessage(SetSweepDataListMessage)



_SIMULATIONSETUPINFOSERVICE = _descriptor.ServiceDescriptor(
  name='SimulationSetupInfoService',
  full_name='ansys.api.edb.v1.SimulationSetupInfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=387,
  serialized_end=692,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSimulationSettings',
    full_name='ansys.api.edb.v1.SimulationSetupInfoService.GetSimulationSettings',
    index=0,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSweepDataList',
    full_name='ansys.api.edb.v1.SimulationSetupInfoService.GetSweepDataList',
    index=1,
    containing_service=None,
    input_type=edb__messages__pb2._EDBOBJMESSAGE,
    output_type=_SWEEPDATALISTMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetSweepDataList',
    full_name='ansys.api.edb.v1.SimulationSetupInfoService.SetSweepDataList',
    index=2,
    containing_service=None,
    input_type=_SETSWEEPDATALISTMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATIONSETUPINFOSERVICE)

DESCRIPTOR.services_by_name['SimulationSetupInfoService'] = _SIMULATIONSETUPINFOSERVICE

# @@protoc_insertion_point(module_scope)
