# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_messages_pb2 as edb__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import simulation_settings_pb2 as simulation__settings__pb2


class HFSSSimulatonSettingsServiceStub(object):
  """DEPRECATED: use SimulationSetupService instead
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAdaptiveSettings = channel.unary_unary(
        '/ansys.api.edb.v1.HFSSSimulatonSettingsService/GetAdaptiveSettings',
        request_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )
    self.SetMeshOperations = channel.unary_unary(
        '/ansys.api.edb.v1.HFSSSimulatonSettingsService/SetMeshOperations',
        request_serializer=simulation__settings__pb2.SetMeshOperationsMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class HFSSSimulatonSettingsServiceServicer(object):
  """DEPRECATED: use SimulationSetupService instead
  """

  def GetAdaptiveSettings(self, request, context):
    """Gets the HFSSAdaptiveSettings  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMeshOperations(self, request, context):
    """Sets the MeshOperation list
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HFSSSimulatonSettingsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAdaptiveSettings': grpc.unary_unary_rpc_method_handler(
          servicer.GetAdaptiveSettings,
          request_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
      'SetMeshOperations': grpc.unary_unary_rpc_method_handler(
          servicer.SetMeshOperations,
          request_deserializer=simulation__settings__pb2.SetMeshOperationsMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.HFSSSimulatonSettingsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
