# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import term_pb2 as term__pb2


class TerminalServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetReference = channel.unary_unary(
        '/ansys.api.edb.v1.TerminalService/SetReference',
        request_serializer=term__pb2.TermSetRefMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )


class TerminalServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetReference(self, request, context):
    """Sets a reference on point term
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetReference': grpc.unary_unary_rpc_method_handler(
          servicer.SetReference,
          request_deserializer=term__pb2.TermSetRefMessage.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.TerminalService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
