# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: term.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='term.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nterm.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\"|\n\x11TermSetRefMessage\x12\x34\n\x0bsource_term\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x31\n\x08ref_term\x18\x02 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage2d\n\x0fTerminalService\x12Q\n\x0cSetReference\x12#.ansys.api.edb.v1.TermSetRefMessage\x1a\x1a.google.protobuf.BoolValue\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,])




_TERMSETREFMESSAGE = _descriptor.Descriptor(
  name='TermSetRefMessage',
  full_name='ansys.api.edb.v1.TermSetRefMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_term', full_name='ansys.api.edb.v1.TermSetRefMessage.source_term', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref_term', full_name='ansys.api.edb.v1.TermSetRefMessage.ref_term', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=176,
)

_TERMSETREFMESSAGE.fields_by_name['source_term'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_TERMSETREFMESSAGE.fields_by_name['ref_term'].message_type = edb__messages__pb2._EDBOBJMESSAGE
DESCRIPTOR.message_types_by_name['TermSetRefMessage'] = _TERMSETREFMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TermSetRefMessage = _reflection.GeneratedProtocolMessageType('TermSetRefMessage', (_message.Message,), {
  'DESCRIPTOR' : _TERMSETREFMESSAGE,
  '__module__' : 'term_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.TermSetRefMessage)
  })
_sym_db.RegisterMessage(TermSetRefMessage)



_TERMINALSERVICE = _descriptor.ServiceDescriptor(
  name='TerminalService',
  full_name='ansys.api.edb.v1.TerminalService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=178,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetReference',
    full_name='ansys.api.edb.v1.TerminalService.SetReference',
    index=0,
    containing_service=None,
    input_type=_TERMSETREFMESSAGE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TERMINALSERVICE)

DESCRIPTOR.services_by_name['TerminalService'] = _TERMINALSERVICE

# @@protoc_insertion_point(module_scope)
