# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edb_messages_pb2 as edb__messages__pb2
import via_group_pb2 as via__group__pb2


class ViaGroupServiceStub(object):
  """ViaGroup service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/ansys.api.edb.v1.ViaGroupService/Create',
        request_serializer=via__group__pb2.ViaGroupCreationMessage.SerializeToString,
        response_deserializer=edb__messages__pb2.EDBObjMessage.FromString,
        )


class ViaGroupServiceServicer(object):
  """ViaGroup service definition
  """

  def Create(self, request, context):
    """Creates a ViaGroup
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ViaGroupServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=via__group__pb2.ViaGroupCreationMessage.FromString,
          response_serializer=edb__messages__pb2.EDBObjMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.edb.v1.ViaGroupService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
