# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: via_group.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edb_messages_pb2 as edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = edb__messages__pb2.google.protobuf.empty_pb2
import point_data_pb2 as point__data__pb2
import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='via_group.proto',
  package='ansys.api.edb.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fvia_group.proto\x12\x10\x61nsys.api.edb.v1\x1a\x12\x65\x64\x62_messages.proto\x1a\x10point_data.proto\x1a\nrefs.proto\"\xf7\x01\n\x17ViaGroupCreationMessage\x12/\n\x06layout\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12/\n\x06points\x18\x02 \x01(\x0b\x32\x1f.ansys.api.edb.v1.PointsMessage\x12\x1a\n\x12\x63onductivity_ratio\x18\x03 \x01(\x01\x12\x30\n\x05layer\x18\x04 \x01(\x0b\x32!.ansys.api.edb.v1.LayerRefMessage\x12,\n\x03net\x18\x05 \x01(\x0b\x32\x1f.ansys.api.edb.v1.NetRefMessage2i\n\x0fViaGroupService\x12V\n\x06\x43reate\x12).ansys.api.edb.v1.ViaGroupCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[edb__messages__pb2.DESCRIPTOR,point__data__pb2.DESCRIPTOR,refs__pb2.DESCRIPTOR,])




_VIAGROUPCREATIONMESSAGE = _descriptor.Descriptor(
  name='ViaGroupCreationMessage',
  full_name='ansys.api.edb.v1.ViaGroupCreationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='ansys.api.edb.v1.ViaGroupCreationMessage.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='ansys.api.edb.v1.ViaGroupCreationMessage.points', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conductivity_ratio', full_name='ansys.api.edb.v1.ViaGroupCreationMessage.conductivity_ratio', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='ansys.api.edb.v1.ViaGroupCreationMessage.layer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net', full_name='ansys.api.edb.v1.ViaGroupCreationMessage.net', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=335,
)

_VIAGROUPCREATIONMESSAGE.fields_by_name['layout'].message_type = edb__messages__pb2._EDBOBJMESSAGE
_VIAGROUPCREATIONMESSAGE.fields_by_name['points'].message_type = point__data__pb2._POINTSMESSAGE
_VIAGROUPCREATIONMESSAGE.fields_by_name['layer'].message_type = refs__pb2._LAYERREFMESSAGE
_VIAGROUPCREATIONMESSAGE.fields_by_name['net'].message_type = refs__pb2._NETREFMESSAGE
DESCRIPTOR.message_types_by_name['ViaGroupCreationMessage'] = _VIAGROUPCREATIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ViaGroupCreationMessage = _reflection.GeneratedProtocolMessageType('ViaGroupCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _VIAGROUPCREATIONMESSAGE,
  '__module__' : 'via_group_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.ViaGroupCreationMessage)
  })
_sym_db.RegisterMessage(ViaGroupCreationMessage)



_VIAGROUPSERVICE = _descriptor.ServiceDescriptor(
  name='ViaGroupService',
  full_name='ansys.api.edb.v1.ViaGroupService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=337,
  serialized_end=442,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.edb.v1.ViaGroupService.Create',
    index=0,
    containing_service=None,
    input_type=_VIAGROUPCREATIONMESSAGE,
    output_type=edb__messages__pb2._EDBOBJMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIAGROUPSERVICE)

DESCRIPTOR.services_by_name['ViaGroupService'] = _VIAGROUPSERVICE

# @@protoc_insertion_point(module_scope)
